version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./data/docker/volumes/pg/:/var/lib/pg

  localstack:
    image: localstack/localstack:latest
    environment:
      DEBUG: 1
      LAMBDA_DOCKER_NETWORK: my-local-aws-network
      LAMBDA_REMOTE_DOCKER: 0
      SERVICES: s3
    ports:
      - 4566:4566
    volumes:
      - ./data/docker/volumes/localstack/var/run/docker.sock:/var/run/docker.sock

  cognito:
    image: jagregory/cognito-local:latest
    ports:
      - 9229:9229
    volumes:
      - ./data/docker/volumes/.cognito:/app/.cognito
